{% set name = "qpoases" %}
{% set version = "3.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/coin-or/qpOASES/archive/refs/tags/releases/{{ version }}.tar.gz
  sha256: e36d795a17b067ea333793d96f17a14fb2bfbd92a4ab86c7f6f513cd9e3e640d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - ninja

test:
  commands:
    - test -f ${PREFIX}/include/qpOASES.hpp  # [not win]
    - test -f ${PREFIX}/lib/libqpOASES.so  # [linux]
    - test -f ${PREFIX}/lib/libqpOASES.dylib  # [osx]
    - if not exist %PREFIX%\\Library\\include\\qpOASES.hpp exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\qpOASES.lib exit 1  # [win]
    # Compilation of Windows shared library is not supported (see https://github.com/coin-or/qpOASES/pull/109)
    # - if not exist %PREFIX%\\Library\\bin\\qpOASES.dll exit 1  # [win]

  imports:
    - qpoases

about:
  home: https://github.com/coin-or/qpOASES
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: Open-source C++ implementation of a QP (Quadratic Programming) solver with online active set strategy.

extra:
  recipe-maintainers:
    - traversaro
