build_platform:
  linux_aarch64: linux_aarch64
  linux_ppc64le: linux_ppc64le
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
test_on_native_only: true
conda_forge_output_validation: true
conda_build:
  pkg_format: '2'
